spring:
  rabbitmq:
    virtual-host: /
    username: guest
    password: guest
    port: 5672
    host: 127.0.0.1
    publisher-confirm-type: correlated
    publisher-returns: true
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/test_jpa
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 127.0.0.1
    lettuce:
      pool:
        #控制一个pool可分配多少个jedis实例，通过pool:
        #getResource()来获取；如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted:
        max-active: 8
        #表示当borrow一个jedis实例时，最大的等待时间，如果超过等待时间，则直接抛JedisConnectionException；
        max-wait: -1
        #控制一个pool最多有多少个状态为idle(空闲)的jedis实例
        max-idle: 8
        min-idle: 0
      shutdown-timeout: 100
task:
  pool:
    corePoolSize: 10
    maxPoolSize: 30
    keepAliveSeconds: 300
    queueCapacity: 500
student:
  name: lk


mybatis:
  type-aliases-package: com.example.rabbit.demo.notice.mybaties.model
  mapper-locations=classpath: classpath*:com/example/rabbit/demo/notice/mybaties/dao/*.xml

